# Generated by Django 6.1.1 on 2026-09-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Apparel', 'Apparel'), ('Equipment', 'Equipment'), ('Nutrition', 'Nutrition'), ('Accessories', 'Accessories')], max_length=20),
        ),
    ]
